from __future__ import annotations

import argparse
import ipaddress
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any


_BACKEND_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_.-]{0,252}")
_HOST_RE = re.compile(
    r"[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?",
)
_WILDCARD_LISTENERS = {"*", "0.0.0.0", "::", "[::]"}


def _network_reachable_listener(value: Any) -> bool:
    address = str(value).strip().strip("[]")
    if str(value).strip() in _WILDCARD_LISTENERS:
        return True
    try:
        return not ipaddress.ip_address(address).is_loopback
    except ValueError:
        return False


def _port(value: Any, name: str, *, disabled_allowed: bool = False) -> int:
    try:
        port = int(str(value).strip() or "0")
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} must be an integer") from exc
    minimum = 0 if disabled_allowed else 1
    if not minimum <= port <= 65535:
        suffix = " or 0 to disable" if disabled_allowed else ""
        raise ValueError(f"{name} must be between 1 and 65535{suffix}")
    return port


def render_caddyfile(
    payload: Any,
    *,
    https_start: Any,
    spacing: Any,
    backend: str,
    host: str,
    preferred_port: Any = 11000,
) -> str:
    start = _port(https_start, "CITADEL_CADDY_HTTPS_START", disabled_allowed=True)
    if start == 0:
        return "# CITADEL central Caddy export is disabled.\n"

    step = _port(spacing, "CITADEL_CADDY_RANGE")
    preferred = _port(preferred_port, "CITADEL_WEBUI_PORT")
    backend = str(backend).strip()
    host = str(host).strip().rstrip(".")
    if not _BACKEND_RE.fullmatch(backend):
        raise ValueError("CITADEL_CADDY_BACKEND must be a container DNS name")
    if not _HOST_RE.fullmatch(host):
        raise ValueError("CITADEL_CADDY_HOST must be a DNS hostname")
    for value, name in ((backend, "CITADEL_CADDY_BACKEND"), (host, "CITADEL_CADDY_HOST")):
        try:
            ipaddress.ip_address(value)
        except ValueError:
            continue
        raise ValueError(f"{name} must not be an IP address")
    if not isinstance(payload, dict):
        raise ValueError("services payload must be a JSON object")

    by_port: dict[int, dict[str, Any]] = {}
    https_only = payload.get("https_only") is True
    for raw in payload.get("http_services") or []:
        if not isinstance(raw, dict) or raw.get("origin") == "host":
            continue
        addrs = raw.get("addrs")
        if isinstance(addrs, list) and addrs and not any(
            _network_reachable_listener(addr) for addr in addrs
        ):
            continue
        try:
            internal_port = _port(raw.get("port"), "service port")
        except ValueError:
            continue
        scheme = str(raw.get("scheme") or "").strip().lower()
        if scheme not in {"http", "https"}:
            continue
        if https_only and scheme != "https":
            continue
        by_port.setdefault(internal_port, raw)

    services = sorted(
        by_port.values(),
        key=lambda item: (
            0 if int(item["port"]) == preferred else 1,
            int(item["port"]),
        ),
    )
    if services and start + (len(services) - 1) * step > 65535:
        raise ValueError("central Caddy port allocation exceeds 65535")

    lines = [
        "# Generated by CITADEL from the latest successful service scan.",
        "# Do not edit this file; configure CITADEL_CADDY_* instead.",
        "",
    ]
    for index, service in enumerate(services):
        public_port = start + index * step
        internal_port = int(service["port"])
        scheme = str(service["scheme"]).lower()
        title = str(service.get("title") or service.get("name") or f"Port {internal_port}")
        title = " ".join(title.replace("#", "").split())[:120]
        lines.extend([
            f"# {title}: {public_port} -> {backend}:{internal_port}",
            (
                f"https://{host}:{public_port}, https://localhost:{public_port}, "
                f"https://127.0.0.1:{public_port} {{"
            ),
        ])
        if scheme == "https":
            lines.extend([
                f"\treverse_proxy https://{backend}:{internal_port} {{",
                "\t\ttransport http {",
                "\t\t\ttls_insecure_skip_verify",
                "\t\t}",
                "\t}",
            ])
        else:
            lines.append(f"\treverse_proxy {backend}:{internal_port}")
        lines.extend(["}", ""])
    return "\n".join(lines)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        temporary.chmod(0o644)
        os.replace(temporary, path)
        try:
            directory_fd = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        except (AttributeError, OSError):
            return
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
    except Exception:
        temporary.unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--services", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--https-start", required=True)
    parser.add_argument("--spacing", required=True)
    parser.add_argument("--backend", default="")
    parser.add_argument("--host", default="")
    parser.add_argument("--preferred-port", default="11000")
    args = parser.parse_args()
    with args.services.open(encoding="utf-8") as handle:
        payload = json.load(handle)
    content = render_caddyfile(
        payload,
        https_start=args.https_start,
        spacing=args.spacing,
        backend=args.backend,
        host=args.host,
        preferred_port=args.preferred_port,
    )
    atomic_write(args.output, content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
